const deploymentConfig = require("../../package.json");

module.exports = {
  menuPath: 'GP4You Components',
  Grouped: true,
  showDisabledGps: false,
  VIEW_HOME: "home",
  VIEW_TASKS: "tasks",
  VIEW_NOTIFICATIONS: "notifications",
  VIEW_REQUESTS: "requests",
  VIEW_REPORTS: "reports",
  VIEW_CLOSEDTASKFORM: "closedtaskform",
  VIEW_TASKFORM: "taskform",
  VIEW_REQUESTFORM: "requestform",
  VIEW_NOTIFFORM: "notifform",
  VIEW_REPORTFORM: "reportform",
  VIEW_RESET_PASSWORD: "reset-password",
  VIEW_CHANGE_PASSWORD: "change-password",
  VIEW_NO_ROLES: "no-roles",
  VIEW_LOGIN_PAGE: "login",
  VIEW_LOGIN_SECONDARY: "adminlogin",
  VIEW_DEFAULT_ENTRY: "login",
  VIEW_LOGIN_SSO: "sso-response",
  VIEW_LOGIN_SSO_ENTRY: "sso-entry",
  VIEW_LOGOUT: "logout",
  DMSIndex: "DMSIndex",
  DMSMaxRowCount: 100,
  CMSIndex: "CMSIndex",
  DelegationIndex: "DelegationIndex",
  delegationType: "partager", // "partager" for sharing, "donnee" for individual use. It depends on rol template configuration.
  TransmissionIndex: "TransmissionIndex",
  DetailsEmployee: "DetailsEmployee",
  ConfigPage: "Config",
  DocumentsIndex: "DocumentsIndex",
  LOGIN_MODULE: "standardLoginModule", // ldapLoginModule
  LOGIN_URL: "login",
  CATEGORY_EMPLOYEE: "SSEMP",
  CATEGORY_MANAGER: "SSMNG",
  isValidationEnabled: true,
  REQUEST_SUCCESS: "OK",
  DATE_FORMAT: "DD/MM/Y",
  FRONT_WS_URL: process.env.PUBLIC_URL,
  VERSION: deploymentConfig.version,
  NAME: deploymentConfig.name,
  AUTHOR: deploymentConfig.author,
  WS_URL: process.env.WS_URL,
  WS_URL_SSO: `${process.env.WS_URL}sso?loginModuleHint=samlLoginModule`,
  WS_URL_CISIRH: `${process.env.WS_URL}business-services/`,
  WS_URL_ACTIVITY: "gpmenu?path=",
  CODESFROMLINK_SOURCE: "codesfromlink",
  DATAFROMDIRECTORY_SOURCE: "datafromdirectory",
  DATAFROMLINK_SOURCE: "datafromlink",
  SESSIONS_MAX_LENGTH: "99",
  DATAFROMDIRECTORY_SOURCE_TASK: "datafromdirectoryTask",
  DATAFROMLINK_SOURCE_TASK: "datafromlinkTask",
  DATAFROMLINK_SOURCE_TASK_LABEL_WITH_KEY: "datafromlinkTaskLabelWithKey",
  DATAFROMDIRECTORY_SOURCE_TASK_LABEL_WITH_KEY: "datafromdirectoryTaskLabelWithKey",
  DATAFROMDIRECTORY_SOURCE_LABEL_WITH_KEY: "datafromdirectoryUrlLabelWithKey",
  DATAFROMLINK_SOURCE_LABEL_WITH_KEY: "datafromlinkLabelWithKey",
  DATAFROMLINK_SOURCE_TASK_WITH_LABEL_KEY: "datafromlinkTaskWithLabelKey",
  LONG: "ZD01LIBLON",
  COURT: "ZD01LIBABR",
  ABSENCES_TYPE: "MTSE",
  ABSENCES_ASC: "ASC",
  ABSENCES_PIF: "PIF",
  PADPROCESS: "AS001",
  DMSPROCESS: "AS100",
  DMSBLOBDATASECTION: "YQ01",
  DMSBLOBDATAITEM: "BLOBRS",
  SUPPORTED_LANGUAGES: ["en", "fr", "es", "it", "de", "ne", "be"],
  // GPs that you don't want to be refreshed once you submit your data. ie: with error message "There's already a request"
  NOT_REFRESHING_ON_SUBMIT_GPS: [
    "MAW00FE0",
    "MAW00IE0",
    "MAW018E0",
    "MAW0E5E0",
    "ASW018E0",
    "AIW400M2",
    "ASW03OP2",
    "ASW000E0",
    "ASW0ESE0",
    "ASW00FE0",
    "ASW0E5E0",
    "ASW0PPE0",
    "ASW00IE0",
    "ASW03DE0",
    "ESW018E0",
    "ESW00FE0",
    "ESW0PPE0",
    "ESW0E5E0",
    "ESW00IE0",
    "ESW0NIE0",
    "GSW00FE0",
    "GSW0E5E0",
    "GSW0PPE0",
    "GSW018E0",
    "GSW0AGE0"
  ],
  PAGINATION_SIZE: 99,
  TRAINING_GP: ["ATWV00E1", "ATWV00M1"],
  TELEWORKING_GPs: ["ASCSAL01"],
  PATHS_WITH_BIG_DISPLAY_OPTION: ["/ASD640MW", "/ASC647M1", "/ASC648M1", "/ASD640MT", "/ASC640M2", "/ASD641MT", "/ASC641M2", "/ASD641MW", "/ASC641M2"],
  HANDLED_ERROR_CODES: ["FRSTCN", "GERRAW", "BPWDFR", "error-315", "error-no-gpid", "error-no-gp-entity", "error-startpop", "error-security"],
  LOGIN_MODULES: [
    { item: "UC10", value: "standardLoginModule" },
    { item: "LDAP", value: "ldapLoginModule" }
  ],
  ALLOWED_UPLOAD_TYPES: ["image/png", "image/jpeg", "application/pdf"],
  FETCH_INTERVAl: 50 * 60 * 1000,
  DELAY_FROM_DIRECTORY: 200, //ms
  widgetsConfig: {
    YOUTUBE: {
      youtubePreference: false,
      videoid: ""
    },
    FB: {
      active: false,
      src:
        "https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FSopraHR%2F&tabs=timeline&width=200px&height=70px&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId"
    },
    TWITTER: {
      active: true,
      sourceType: "profile",
      screenName: "sopraHR",
      username: "Sopra HR"
    },
    SESSION_TIMEOUT_TIMER: 1800, // 30 minute
    WARNING_TIMER: 10, // s
    EOTM: {
      active: false,
      name: "George Darkos",
      subName: "Full Stack Web Developper",
      title: "Hello there !",
      description:
        "i am a full stack web developper. imainly work with PHP, CSS, JS and wordPress. I also play well with Photoshop, corel Draw, after Effects and other cool stuff",
      img: "https://randomuser.me/api/portraits/men/99.jpg"
    }
  },
  carousselConfig: [
    {
      title: "LE CPAS DE SCHAERBEEK",
      description: "« Toute personne a droit à l'aide sociale. Celle-ci a pour but de permettre à chacun de mener une vie conforme à la dignité humaine »",
      details: "",
      button: "visitez",
      image: "",
      url: "https://www.1030.be/fr/vivre-ensemble-solidarite/cpas/le-cpas-de-schaerbeek"
    },
    {
      title: "Sopra HR Software 2019",
      description:
        "Sopra HR Software, filiale de Sopra Steria, offre des solutions RH complètes parfaitement adaptées aux besoin des Directions des Ressources Humaines et aux organisations de moyennes et grandes tailles, des secteurs public et privé",
      details: "",
      button: "Lire plus",
      image: "",
      url: "https://www.soprahr.com/fr"
    }
  ],
  MODEL_145_LINK: "https://www.agenciatributaria.es/static_files/Sede/Procedimiento_ayuda/G603/mod145_es_es.pdf",
  // feature activation
  isPasswordStrengthCheckEnabled: false,
  isReportsEnabled: true,
  isUserAvatarEnabled: false,
  isPrintItEnable: false,
  isSidebarEnabled: false,
  isDelegationEnabled: true,
  isLanguageSelectorEnabled: true,
  shouldShowUserPic: true,
  shouldShowUserName: true,
  shouldShowUserMatcle: true,
  shouldShowUserNumber: false,
  isVideoEnabled: false,
  isWidgetEnabled: false,
  isFixedPluginEnabled: true,
  isCarousselEnabled: false,
  isIngentisActive: false,
  isPlanSagaActive: false,
  isHeaderBoxEnabled: false,
  isActivitySummaryEnabled: false,
  isSSOEnabled: false,
  //subordinate search
  isSearchMatcleEnabled: true,
  isSearchNmpresEnabled: true,
  isSearchNoidenEnabled: true,
  isSearchUnitEnabled: true,
  isGlobalSubordinateEnabled: false,
  showPendingAbsences: true,
  showEmployeePicture: true,
  showLoadingAnimation: true,
  isSearchCenterEnabled: false,
  isSearchPolyvalenceEnabled: false,
  isSearchPositionEnabled: false,
  isResetPasswordEnabled: false,
  isChangePasswordEnabled: true,

};
